// packages/grapys-react/src/views/Chat.tsx
import React from "react";
import { GUIMessage } from "../utils/gui/type";

interface ChatProps {
  messages: GUIMessage[];
  isStreaming: Record<string, boolean>;
  streamData: Record<string, string>;
  streamNodeIds: string[];
}

const Chat: React.FC<ChatProps> = ({ messages, isStreaming, streamData, streamNodeIds }) => {
  return (
    <div className="m-auto w-10/12 text-left">
      {messages.map((m, k) => (
        <div key={k}>
          {m.role === "user" ? (
            <div className="mr-8">👱{m.content}</div>
          ) : (
            <div className="ml-20">
              🤖({m.nodeId}){m.content}
            </div>
          )}
        </div>
      ))}
      {streamNodeIds.map((nodeId, k) => (
        <div key={k}>
          {isStreaming[nodeId] && (
            <div className="ml-20">
              🤖({nodeId}){streamData[nodeId]}
            </div>
          )}
        </div>
      ))}
    </div>
  );
};

export default Chat;

// packages/grapys-vue/src/components/Chat.vue
<template>
  <div class="m-auto w-10/12 text-left">
    <div v-for="(m, k) in messages" :key="k">
      <div v-if="m.role === 'user'" class="mr-8">👱{{ m.content }}</div>
      <div class="ml-20" v-else>🤖({{ m.nodeId }}){{ m.content }}</div>
    </div>
    <div v-for="(nodeId, k) in streamNodeIds" :key="k">
      <div class="ml-20" v-if="isStreaming[nodeId]">🤖({{ nodeId }}){{ streamData[nodeId] }}</div>
    </div>
  </div>
</template>
<script lang="ts">
import { defineComponent, PropType } from "vue";
import { GUIMessage } from "../utils/gui/type";

export default defineComponent({
  props: {
    messages: {
      type: Array<GUIMessage>,
      default: () => [],
    },
    isStreaming: {
      type: Object as PropType<Record<string, boolean>>,
      default: () => {
        return {};
      },
    },
    streamData: {
      type: Object as PropType<Record<string, string>>,
      default: () => {
        return {};
      },
    },
    streamNodeIds: {
      type: Array<string>,
      default: () => [],
    },
  },
});
</script>
