// packages/grapys-react/src/views/ContextNodeMenu.tsx
import { forwardRef, useImperativeHandle, useState, useRef } from "react";
import { useLocalStore } from "../store/index";

import ContextMenu from "./ContextMenu";

const EdgeContextMenu = forwardRef((__, ref) => {
  const contextMenuRef = useRef<{ openMenu: (event: MouseEvent | TouchEvent, rect: DOMRect) => void; closeMenu: () => void } | null>(null);
  const [selectedNodeIndex, setSelectedNodeIndex] = useState(0);
  const deleteNode = useLocalStore((state) => state.deleteNode);

  useImperativeHandle(ref, () => ({
    openMenu: (event: React.MouseEvent | React.TouchEvent, rect: DOMRect, nodeIndex: number) => {
      event.preventDefault();
      contextMenuRef.current?.openMenu(event as MouseEvent, rect);
      setSelectedNodeIndex(nodeIndex);
    },
    closeMenu: () => {
      contextMenuRef.current?.closeMenu();
    },
  }));

  return (
    <ContextMenu ref={contextMenuRef} className="z-100">
      <li className="cursor-pointer px-4 py-2 hover:bg-gray-100" onClick={() => deleteNode(selectedNodeIndex)}>
        Delete
      </li>
    </ContextMenu>
  );
});

export default EdgeContextMenu;

// packages/grapys-vue/src/views/ContextNodeMenu.vue
<template>
  <ContextMenu ref="contextMenu" class="z-100">
    <li class="cursor-pointer px-4 py-2 hover:bg-gray-100" @click="deleteNode()">Delete</li>
  </ContextMenu>
</template>

<script lang="ts">
import { ref, defineComponent } from "vue";

import ContextMenu from "./ContextMenu.vue";
import { useStore } from "../store";

export default defineComponent({
  components: {
    ContextMenu,
  },
  setup() {
    const contextMenu = ref();

    const store = useStore();
    const selectedNodeIndex = ref(0);

    const openMenu = (event: MouseEvent | TouchEvent, rect: DOMRect, nodeIndex: number) => {
      event.preventDefault();
      contextMenu.value.openMenu(event, rect);
      selectedNodeIndex.value = nodeIndex;
    };

    const closeMenu = () => {
      contextMenu.value.closeMenu();
    };

    const deleteNode = () => {
      store.deleteNode(selectedNodeIndex.value);
    };
    return {
      contextMenu,
      openMenu,
      closeMenu,
      deleteNode,
    };
  },
});
</script>
