// packages/grapys-react/src/views/ContextMenu.tsx
import { useState, useRef, forwardRef, useImperativeHandle } from "react";
import { getClientPos } from "../utils/gui/utils";

type ContextMenuHandle = {
  openMenu: (event: React.MouseEvent | React.TouchEvent, rect: DOMRect) => void;
  closeMenu: () => void;
};

type ContextMenuProps = {
  children: React.ReactNode;
};


const ContextMenu = forwardRef<ContextMenuHandle, ContextMenuProps>(({ children }, ref) => {
  const [menuVisible, setMenuVisible] = useState(false);
  const [menuStyle, setMenuStyle] = useState({ top: "0px", left: "0px" });
  const menuRef = useRef(null);

  useImperativeHandle(ref, () => ({
    openMenu: (event:  React.MouseEvent | React.TouchEvent, rect: DOMRect) => {
      event.preventDefault();
      const { clientX, clientY } = getClientPos(event);
      setMenuStyle({
        top: `${clientY - rect.top}px`,
        left: `${clientX - rect.left}px`,
      });
      setMenuVisible(true);
    },
    closeMenu: () => {
      setMenuVisible(false);
    },
  }));

  return (
    <>
      {menuVisible && (
        <ul ref={menuRef} style={menuStyle} className="absolute w-40 rounded-md border border-gray-300 bg-white py-2 shadow-md">
          {children}
        </ul>
      )}
    </>
  );
});

export default ContextMenu;

// packages/grapys-vue/src/views/ContextMenu.vue
<template>
  <ul v-if="menuVisible" :style="menuStyle" class="absolute bg-white border border-gray-300 shadow-md rounded-md py-2 w-40">
    <slot />
  </ul>
</template>

<script lang="ts">
import { ref, defineComponent } from "vue";

import { getClientPos } from "../utils/gui/utils";

export default defineComponent({
  setup() {
    const menuVisible = ref(false);
    const menuStyle = ref({ top: "0px", left: "0px" });

    const openMenu = (event: MouseEvent | TouchEvent, rect: DOMRect) => {
      event.preventDefault();
      const { clientX, clientY } = getClientPos(event);
      menuStyle.value = {
        top: `${clientY - rect.top}px`,
        left: `${clientX - rect.left}px`,
      };
      menuVisible.value = true;
    };

    const closeMenu = () => {
      menuVisible.value = false;
    };

    return {
      menuVisible,
      menuStyle,
      openMenu,
      closeMenu,
    };
  },
});
</script>
