// packages/grapys-react/src/views/ContextEdgeMenu.tsx
import { useRef, useState, forwardRef, useImperativeHandle } from "react";
import ContextMenu from "./ContextMenu";
import { useLocalStore } from "../store/index";

type ContextEdgeMenuHandle = {
  openMenu: (event: React.MouseEvent | React.TouchEvent, rect: DOMRect) => void;
  closeMenu: () => void;
};

const ContextEdgeMenu = forwardRef((__, ref) => {
  const contextMenuRef = useRef<ContextEdgeMenuHandle | null>(null);
  const [selectedEdgeIndex, setSelectedEdgeIndex] = useState(0);
  const deleteEdge = useLocalStore((state) => state.deleteEdge);

  useImperativeHandle(ref, () => ({
    openMenu: (event:  React.MouseEvent | React.TouchEvent, rect: DOMRect, edgeIndex: number) => {
      event.preventDefault();
      contextMenuRef.current?.openMenu(event, rect);
      setSelectedEdgeIndex(edgeIndex);
    },
    closeMenu: () => {
      contextMenuRef.current?.closeMenu();
    },
  }));

  const _deleteEdge = () => {
    deleteEdge(selectedEdgeIndex);
  };

  return (
    <ContextMenu ref={contextMenuRef}>
      <li className="cursor-pointer px-4 py-2 hover:bg-gray-100" onClick={_deleteEdge}>
        Delete
      </li>
    </ContextMenu>
  );
});

export default ContextEdgeMenu;

// packages/grapys-vue/src/views/ContextEdgeMenu.vue
<template>
  <ContextMenu ref="contextMenu">
    <li class="cursor-pointer px-4 py-2 hover:bg-gray-100" @click="deleteEdge()">Delete</li>
  </ContextMenu>
</template>

<script lang="ts">
import { ref, defineComponent } from "vue";

import ContextMenu from "./ContextMenu.vue";
import { useStore } from "../store";

export default defineComponent({
  components: {
    ContextMenu,
  },
  setup() {
    const contextMenu = ref();

    const store = useStore();
    const selectedEdgeIndex = ref(0);

    const openMenu = (event: MouseEvent | TouchEvent, rect: DOMRect, edgeIndex: number) => {
      event.preventDefault();
      contextMenu.value.openMenu(event, rect);
      selectedEdgeIndex.value = edgeIndex;
    };

    const closeMenu = () => {
      contextMenu.value.closeMenu();
    };

    const deleteEdge = () => {
      store.deleteEdge(selectedEdgeIndex.value);
    };
    return {
      contextMenu,
      openMenu,
      closeMenu,
      deleteEdge,
    };
  },
});
</script>
