// packages/grapys-react/src/views/GUI.tsx
import { FC, useEffect, useMemo, useRef } from "react";

import Node from "./Node";
import Edge from "./Edge";
import Loop from "./Loop";

import AddNode from "./AddNode";
import ContextEdgeMenu from "./ContextEdgeMenu";
import ContextNodeMenu from "./ContextNodeMenu";

import GraphRunner from "./GraphRunner";
import TemplateGraph from "./TemplateGraph";

// import { EdgeData, NodePosition, UpdateStaticValue } from "../utils/gui/type";

import { graphChat } from "../graph/chat_tinyswallow";

import { useNewEdge } from "../composable/gui";
import { graphToGUIData, guiEdgeData2edgeData, handleDownload } from "../utils/gui/utils";
import { GraphData, sleep } from "graphai";
import { useLocalStore, node2Record, toGraph } from "../store/index";

const GUI: FC = () => {
  const nodes = useLocalStore((state) => state.nodes());
  const edges = useLocalStore((state) => state.edges());
  const currentData = useLocalStore((state) => state.currentData);
  const nodeRecords = useMemo(() => node2Record(nodes), [nodes]);
  const edgeDataList = useMemo(() => guiEdgeData2edgeData(edges, nodeRecords), [edges, nodeRecords]);

  const undo = useLocalStore((state) => state.undo);
  const redo = useLocalStore((state) => state.redo);
  const undoable = useLocalStore((state) => state.undoable());
  const redoable = useLocalStore((state) => state.redoable());

  const loadData = useLocalStore((state) => state.loadData);

  const contextNodeMenuRef = useRef<{ openMenu: (event: MouseEvent, rect: DOMRect, nodeIndex: number) => void; closeMenu: () => void } | null>(null);
  const contextEdgeMenuRef = useRef<{ openMenu: (event: MouseEvent, rect: DOMRect, edgeIndex: number) => void; closeMenu: () => void } | null>(null);

  const resetGraph = useLocalStore((state) => state.reset);
  const newGraphData = toGraph(currentData);

  const initData = useLocalStore((state) => state.initData);
  const updateNodePosition = useLocalStore((state) => state.updateNodePosition);
  const onSavePosition = useLocalStore((state) => state.saveNodePositionData);

  const updateGraph = (graph: GraphData) => {
    const { rawEdge, rawNode, loop } = graphToGUIData(graph);
    initData(rawNode, rawEdge, loop);
  };
  useEffect(() => {
    (async () => {
      updateGraph(graphChat);
      await sleep(1);
      onSavePosition();
    })();
  }, []);

  const { svgRef, newEdgeData, onNewEdgeStart, onNewEdge, onNewEdgeEnd, nearestData, edgeConnectable } = useNewEdge();

  const openEdgeMenu = (event: React.MouseEvent, edgeIndex: number) => {
    if (svgRef.current) {
      const rect = svgRef.current.getBoundingClientRect();
      contextEdgeMenuRef.current?.openMenu(event.nativeEvent, rect, edgeIndex);
    }
  };

  const closeMenu = () => {
    contextNodeMenuRef.current?.closeMenu();
    contextEdgeMenuRef.current?.closeMenu();
  };

  const openNodeMenu = (event: React.MouseEvent, nodeIndex: number) => {
    if (svgRef.current) {
      const rect = svgRef.current.getBoundingClientRect();
      contextNodeMenuRef.current?.openMenu(event.nativeEvent, rect, nodeIndex);
    }
  };

  const save = () => {
    const dataStr = JSON.stringify(newGraphData);
    window.localStorage.setItem("GRAPHAIGUI", dataStr);
  };

  const load = () => {
    const data = window.localStorage.getItem("GRAPHAIGUI");
    try {
      if (data) {
        const graphData = JSON.parse(data);
        loadData(graphData.metadata.data);
      }
    } catch (error) {
      console.log(error);
    }
  };

  const setGraph = async (graph: GraphData) => {
    resetGraph();
    await sleep(1);
    updateGraph(graph);
    await sleep(1);
    onSavePosition();
  };

  return (
    <div>
      <div className="flex h-screen w-full">
        <aside className="w-48 p-4 text-center">
          <h2 className="text-lg font-bold">Menu</h2>
          <AddNode />
          <hr />
          <button
            onClick={undo}
            className={`m-1 cursor-pointer items-center rounded-full px-4 py-2 font-bold text-white ${undoable ? "bg-sky-500 hover:bg-sky-700" : "bg-sky-200"}`}
          >
            Undo
          </button>
          <button
            onClick={redo}
            className={`m-1 cursor-pointer items-center rounded-full px-4 py-2 font-bold text-white ${redoable ? "bg-sky-500 hover:bg-sky-700" : "bg-sky-200"}`}
          >
            Redo
          </button>
          <hr />
          <div>
            <button onClick={resetGraph} className="m-1 cursor-pointer items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white">
              Clear Graph
            </button>
          </div>
          <hr />
          <div>
            <button onClick={save} className="m-1 cursor-pointer items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white">
              Save Graph
            </button>
          </div>
          <div>
            <button onClick={load} className="m-1 cursor-pointer items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white">
              Load Graph
            </button>
          </div>
          <div>
            <button
              onClick={() => handleDownload(newGraphData)}
              className="m-1 cursor-pointer items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white"
            >
              Download
            </button>
          </div>
          <hr />
          <TemplateGraph onSetGraph={setGraph} />
        </aside>
        <main className="flex-1">
          <div className="relative h-[100vh] overflow-hidden rounded-md border-4 border-gray-200" onClick={closeMenu}>
            <svg x="0" y="0" className="absolute h-[100%] w-full" ref={svgRef}>
              {edgeDataList.map((edge, index) => (
                <Edge
                  key={`edge-${edge.source}-${edge.target}-${index}`}
                  sourceData={edge.source}
                  targetData={edge.target}
                  index={index}
                  openEdgeMenu={openEdgeMenu}
                />
              ))}
              {newEdgeData && <Edge sourceData={newEdgeData.source} targetData={newEdgeData.target} isConnectable={edgeConnectable} />}{" "}
            </svg>
            <Loop />
            {nodes.map((node, index) => (
              <Node
                key={`${node.nodeId}-${index}`}
                nodeIndex={index}
                nodeData={node}
                nearestData={nearestData}
                onUpdatePosition={(pos) => updateNodePosition(index, pos)}
                onSavePosition={onSavePosition}
                onNewEdgeStart={onNewEdgeStart}
                onNewEdge={onNewEdge}
                onNewEdgeEnd={onNewEdgeEnd}
                onOpenNodeMenu={(e) => openNodeMenu(e, index)}
              />
            ))}
            <ContextNodeMenu ref={contextNodeMenuRef} />
            <ContextEdgeMenu ref={contextEdgeMenuRef} />
          </div>
        </main>
      </div>
      <div>
        <GraphRunner graphData={newGraphData} />
      </div>
      {JSON.stringify(newGraphData, null, 2)}
      <div className="bg-red-200 bg-red-300 bg-red-400 bg-red-500"></div>
      <div className="bg-green-200 bg-green-300 bg-green-400 bg-green-500"></div>
      <div className="bg-blue-200 bg-blue-300 bg-blue-400 bg-blue-500"></div>
      <div className="bg-yellow-200 bg-yellow-300 bg-yellow-400 bg-yellow-500"></div>
      <div className="bg-violet-200 bg-violet-500"></div>
    </div>
  );
};

export default GUI;

// packages/grapys-vue/src/views/GUI.vue
<script lang="ts">
import { defineComponent, computed, onMounted, ref, nextTick } from "vue";
import Node from "./Node.vue";
import Edge from "./Edge.vue";
import Loop from "./Loop.vue";

import AddNode from "./AddNode.vue";
import ContextEdgeMenu from "./ContextEdgeMenu.vue";
import ContextNodeMenu from "./ContextNodeMenu.vue";

import GraphRunner from "./GraphRunner.vue";
import TemplateGraph from "./TemplateGraph.vue";

import { EdgeData, NodePosition, UpdateStaticValue } from "../utils/gui/type";

import { graphChat } from "../graph/chat_tinyswallow";

import { useNewEdge } from "../composable/gui";
import { graphToGUIData, guiEdgeData2edgeData } from "../utils/gui/utils";
import { GraphData } from "graphai";
import { useStore } from "../store";

export default defineComponent({
  components: {
    Node,
    Edge,
    Loop,
    AddNode,
    ContextEdgeMenu,
    ContextNodeMenu,
    GraphRunner,
    TemplateGraph,
  },
  setup() {
    const store = useStore();
    const contextEdgeMenu = ref();
    const contextNodeMenu = ref();

    const updateGraph = (graph: GraphData) => {
      const { rawEdge, rawNode, loop } = graphToGUIData(graph);
      store.initData(rawNode, rawEdge, loop);
    };
    updateGraph(graphChat);

    const setGraph = async (graph: GraphData) => {
      resetGraph();
      await nextTick(); // to reset edge position. Due to duplicate edge keys, the position will be incorrect.
      updateGraph(graph);
    };
    onMounted(() => {
      saveNodePosition();
    });

    const updateNodePosition = (index: number, pos: NodePosition) => {
      store.updateNodePosition(index, pos);
    };
    const saveNodePosition = () => {
      store.saveNodePositionData();
    };
    const updateStaticNodeValue = (index: number, value: UpdateStaticValue, saveHistory: boolean) => {
      store.updateStaticNodeValue(index, value, saveHistory);
    };

    const edgeDataList = computed<EdgeData[]>(() => {
      return guiEdgeData2edgeData(store.edges, store.nodeRecords);
    });

    const { svgRef, newEdgeData, onNewEdgeStart, onNewEdge, onNewEdgeEnd, nearestData, edgeConnectable } = useNewEdge();

    const openEdgeMenu = (event: MouseEvent, edgeIndex: number) => {
      const rect = svgRef.value.getBoundingClientRect();
      contextEdgeMenu.value.openMenu(event, rect, edgeIndex);
    };
    const closeMenu = () => {
      contextEdgeMenu.value.closeMenu();
      contextNodeMenu.value.closeMenu();
    };
    const openNodeMenu = (event: MouseEvent, nodeIndex: number) => {
      const rect = svgRef.value.getBoundingClientRect();
      contextNodeMenu.value.openMenu(event, rect, nodeIndex);
    };

    const resetGraph = () => {
      store.reset();
    };

    const save = () => {
      const dataStr = JSON.stringify(store.graphData);
      window.localStorage.setItem("GRAPHAIGUI", dataStr);
    };

    const load = () => {
      const data = window.localStorage.getItem("GRAPHAIGUI");
      try {
        if (data) {
          const graphData = JSON.parse(data);
          store.loadData(graphData.metadata.data);
        }
      } catch (error) {
        console.log(error);
      }
    };

    return {
      updateNodePosition,
      saveNodePosition,
      updateStaticNodeValue,

      store,

      edgeDataList,
      onNewEdgeStart,
      onNewEdge,
      onNewEdgeEnd,
      newEdgeData,
      svgRef,
      nearestData,

      contextEdgeMenu,
      contextNodeMenu,
      openEdgeMenu,
      openNodeMenu,
      closeMenu,

      edgeConnectable,

      resetGraph,
      save,
      load,

      setGraph,
    };
  },
});
</script>

<template>
  <div>
    <div class="flex h-screen">
      <aside class="w-48 p-4 text-center">
        <h2 class="text-lg font-bold">Menu</h2>

        <AddNode />
        <hr />
        <button
          @click="store.undo"
          class="m-1 items-center rounded-full px-4 py-2 font-bold text-white"
          :class="store.undoable ? 'bg-sky-500 hover:bg-sky-700' : 'bg-sky-200'"
        >
          Undo
        </button>
        <button
          @click="store.redo"
          class="m-1 items-center rounded-full px-4 py-2 font-bold text-white"
          :class="store.redoable ? 'bg-sky-500 hover:bg-sky-700' : 'bg-sky-200'"
        >
          Redo
        </button>
        <hr />
        <div>
          <button @click="resetGraph" class="m-1 items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white">Clear Graph</button>
        </div>
        <hr />

        <div>
          <button @click="save" class="m-1 items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white">Save Graph</button>
        </div>
        <div>
          <button @click="load" class="m-1 items-center rounded-full bg-sky-500 px-4 py-2 font-bold text-white">Load Graph</button>
        </div>
        <hr />
        <TemplateGraph @set-graph="setGraph" />
      </aside>
      <main class="flex-1">
        <div class="relative h-[100vh] overflow-hidden rounded-md border-4 border-gray-200" @click="closeMenu">
          <Loop />
          <svg x="0" y="0" class="pointer-events-none absolute h-[100%] w-full" ref="svgRef">
            <Edge
              v-for="(edge, index) in edgeDataList"
              :key="['edge', edge.source, edge.target, index].join('-')"
              :source-data="edge.source"
              :target-data="edge.target"
              class="pointer-events-auto"
              @dblclick="(e) => openEdgeMenu(e, index)"
            />
            <Edge
              v-if="newEdgeData"
              :source-data="newEdgeData.source"
              :target-data="newEdgeData.target"
              class="pointer-events-auto"
              :is-connectable="edgeConnectable"
            />
          </svg>
          <Node
            v-for="(node, index) in store.nodes"
            :key="[node.nodeId, index].join('-')"
            :node-index="index"
            :node-data="node"
            :nearest-data="nearestData"
            @update-position="(pos) => updateNodePosition(index, pos)"
            @update-static-node-value="(value) => updateStaticNodeValue(index, value, true)"
            @save-position="saveNodePosition"
            @new-edge-start="onNewEdgeStart"
            @new-edge="onNewEdge"
            @new-edge-end="onNewEdgeEnd"
            @open-node-menu="(event) => openNodeMenu(event, index)"
          />
          <ContextEdgeMenu ref="contextEdgeMenu" />
          <ContextNodeMenu ref="contextNodeMenu" />
        </div>
      </main>
    </div>
    <div>
      <GraphRunner />
    </div>
    <div>
      <div class="text-left">
        <pre>
        {{ JSON.stringify(store.graphData, null, 2) }}
      </pre
        >
      </div>
    </div>
    <div>
      <div class="text-left">
        <div v-for="(history, k) in store.histories" :key="k">
          {{ history.name }}
        </div>
      </div>
    </div>
  </div>
</template>
