// packages/grapys-react/src/views/Loop.tsx
import { useEffect, useRef } from "react";
import { useLocalStore } from "../store";

import { agentProfiles } from "../utils/gui/data";
import { getLoopWhileSources } from "../utils/gui/utils

const LoopComponent = () => {
  const nodes = useLocalStore((state) => state.nodes());
  const loop = useLocalStore((state) => state.loop());
  const storeUpdateLoop = useLocalStore((state) => state.updateLoop);
  const countRef = useRef<HTMLInputElement | null>(null);

  const whileSources = getLoopWhileSources(nodes);

  const updateLoop = () => {
    if (loop.loopType === "while") {
      storeUpdateLoop({ loopType: "while", while: loop.while });
    } else if (loop.loopType === "count") {
      storeUpdateLoop({ loopType: "count", count: Number(loop.count) });
    } else {
      storeUpdateLoop({ loopType: "none" });
    }
  };

  useEffect(() => {
    const handleBlur = () => updateLoop();
    if (countRef.current) {
      countRef.current.addEventListener("blur", handleBlur);
    }
    return () => {
      if (countRef.current) {
        countRef.current.removeEventListener("blur", handleBlur);
      }
    };
  }, [countRef]);

  return (
    <div className="absolute flex w-36 cursor-grab flex-col rounded-md bg-green-400 text-center text-white select-none">
      <div className="w-full rounded-t-md bg-green-500 py-1 text-center leading-none">Loop</div>
      <div className="my-4 p-2">
        <select
          className="w-full resize-none rounded-md border border-gray-300 p-1 text-black"
          onChange={(e) => storeUpdateLoop({ ...loop, loopType: e.target.value })}
          value={loop.loopType}
        >
          <option value="none">None</option>
          <option value="while">While</option>
          <option value="count">Count</option>
        </select>

        {loop.loopType === "while" && (
          <div className="mt-2">
            <select
              className="w-full resize-none rounded-md border border-gray-300 p-1 text-black"
              onChange={(e) => storeUpdateLoop({ ...loop, while: e.target.value })}
              value={loop.while || whileSources[0]}
            >
              {whileSources.map((item) => (
                <option key={item} value={item}>
                  {item}
                </option>
              ))}
            </select>
          </div>
        )}

        {loop.loopType === "count" && (
          <div className="mt-2">
            <input
              type="number"
              className="w-full rounded-md border border-gray-300 p-1 text-black"
              ref={countRef}
              value={loop.count || "1"}
              onChange={(e) => storeUpdateLoop({ ...loop, count: Number(e.target.value) })}
            />
          </div>
        )}
      </div>
    </div>
  );
};

export default LoopComponent;

// packages/grapys-vue/src/views/Loop.vue
<template>
  <div class="absolute flex w-36 cursor-grab flex-col rounded-md bg-green-400 text-center text-white select-none">
    <div class="w-full rounded-t-md bg-green-500 py-1 text-center leading-none">Loop</div>
    <div class="my-4 p-2">
      <select class="w-full resize-none rounded-md border border-gray-300 p-1 text-black" @change="updateType" :value="loopType">
        <option value="none">None</option>
        <option value="while">While</option>
        <option value="count">Count</option>
      </select>

      <div v-if="loopType === 'while'" class="mt-2">
        <select class="w-full resize-none rounded-md border border-gray-300 p-1 text-black" @change="updateWhile" :value="whileValue">
          <option v-for="item in whileSources" :key="item">{{ item }}</option>
        </select>
      </div>
      <div v-show="loopType === 'count'" class="mt-2">
        <input type="number" class="w-full rounded-md border border-gray-300 p-1 text-black" ref="countRef" v-model="countValue" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, onMounted, onBeforeUnmount, watch } from "vue";
import { useStore } from "../store";
import { agentProfiles } from "../utils/gui/data";
import { getLoopWhileSources } from "../utils/gui/utils";

export default defineComponent({
  setup() {
    const store = useStore();

    const whileSources = computed(() => {
      return getLoopWhileSources(store.nodes);
    });

    const loopType = ref(store.loop.loopType);
    const countValue = ref("1");
    const whileValue = ref(whileSources.value[0]);
    const countRef = ref();

    const storeLoopData = computed(() => {
      if (loopType.value === "while") {
        return {
          loopType: "while",
          while: whileValue.value,
        };
      }
      if (loopType.value === "count") {
        return {
          loopType: "count",
          count: Number(countValue.value),
        };
      }
      return {
        loopType: "none",
      };
    });
    watch(
      () => store.loop,
      (value) => {
        loopType.value = value.loopType;
        if (value.loopType === "while") {
          whileValue.value = value.while ?? "";
        }
        if (value.loopType === "count") {
          countValue.value = String(value.count ?? 1);
        }
      },
    );

    const updateLoop = () => {
      store.updateLoop(storeLoopData.value);
    };

    const updateType = (event: Event) => {
      if (event.target instanceof HTMLSelectElement) {
        loopType.value = event?.target?.value ?? "";
        updateLoop();
      }
    };
    const updateWhile = (event: Event) => {
      if (event.target instanceof HTMLSelectElement) {
        whileValue.value = event?.target?.value ?? "";
        updateLoop();
      }
    };
    const blurUpdateEvent = () => {
      updateLoop();
    };
    onMounted(() => {
      if (countRef.value) {
        countRef.value.addEventListener("blur", blurUpdateEvent);
      }
    });
    onBeforeUnmount(() => {
      if (countRef.value) {
        countRef.value.removeEventListener("blur", blurUpdateEvent);
      }
    });

    return {
      loopType,
      countValue,
      whileValue,

      whileSources,

      updateType,
      updateWhile,

      countRef,
      store,
    };
  },
});
</script>
