// packages/grapys-vue/src/views/GraphRunner.vue
<template>
  <div>
    <div class="items-center justify-center text-center">
      <div class="mt-2">
        <chat :messages="messages" :is-streaming="isStreaming" :stream-data="streamData" :stream-node-ids="streamNodes" />
      </div>
      <div class="mt-2">
        <button
          class="m-1 items-center rounded-full px-4 py-2 font-bold text-white hover:bg-sky-700" @click="run"
          :disabled="isRunning"
          :class="isRunning ? 'bg-sky-200':'bg-sky-500'"
          >Run</button>
        <button
          class="m-1 items-center rounded-full px-4 py-2 font-bold text-white hover:bg-sky-700" @click="abort"
          :disabled="!isRunning"
          :class="!isRunning ? 'bg-sky-200':'bg-sky-500'"
          >Stop</button>
      </div>

      <div>
        <div class="m-auto my-4 w-10/12">
          <div v-if="events.length > 0" class="hidden font-bold text-red-600">Write message to bot!!</div>
          <div class="flex">
            <input v-model="userInput" class="flex-1 rounded-md border-2 p-2" :disabled="events.length == 0" />
            <button
              class="ml-1 flex-none items-center rounded-md px-4 py-2 font-bold text-white hover:bg-sky-700"
              :class="events.length == 0 ? 'bg-sky-200' : 'bg-sky-500'"
              @click="submitText(events[0])"
            >
              Submit
            </button>
          </div>
        </div>
      </div>
      <div v-if="!ready">Loading web llm model</div>
      <div v-else>Ready!</div>
      <div>
        {{ loading }}
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";
import { GraphAI } from "graphai";

import { useStore } from "../store";

import { useStreamData } from "../utils/vue-plugin/stream";
import { useChatPlugin } from "../utils/vue-plugin/chat";

import Chat from "../components/Chat.vue";

import * as agents from "@graphai/vanilla";
import { openAIAgent } from "@graphai/openai_agent";
import { geminiAgent } from "@graphai/gemini_agent";
import { anthropicAgent } from "@graphai/anthropic_agent";

import tinyswallowAgent, { modelLoad, loadEngine, CallbackReport } from "../agents/tinyswallow";
import { textInputEvent } from "../agents/event";

import { graphConfigs } from "../graph";

export default defineComponent({
  components: {
    Chat,
  },
  setup() {
    const isRunning = ref(false);
    const store = useStore();
    loadEngine();

    const { eventAgent, userInput, events, submitText } = textInputEvent();
    const { messages, chatMessagePlugin } = useChatPlugin();
    const { streamData, streamAgentFilter, streamPlugin, isStreaming } = useStreamData();

    const agentFilters = [
      {
        name: "streamAgentFilter",
        agent: streamAgentFilter,
      },
    ];

    let graphai: GraphAI | null = null;
    const run = async () => {
      isRunning.value = true;
      graphai = new GraphAI(
        store.graphData,
        {
          ...agents,
          openAIAgent,
          anthropicAgent,
          geminiAgent,
          eventAgent,
          tinyswallowAgent,
        },
        {
          agentFilters,
          config: graphConfigs,
        },
      );
      graphai.registerCallback(streamPlugin(store.streamNodes));
      graphai.registerCallback(chatMessagePlugin(store.resultNodes));

      try {
        await graphai.run();
      } catch (error) {
        console.log(error);
      }
    };
    const abort = () => {
      try {
        if (isRunning.value && graphai) {
          graphai.abort();
          // graphai = null;
        }
      } catch (error) {
        console.log(error);
      } finally {
        isRunning.value = false;
      }
    };
    const streamNodes = computed(() => {
      return store.streamNodes;
    });
    const loading = ref("");
    const ready = ref(false);
    modelLoad((report: CallbackReport) => {
      if (report.progress === 1) {
        ready.value = true;
      }
      loading.value = report.text;
      console.log(report.text);
    });

    return {
      run,
      abort,
      isRunning,

      streamData,
      isStreaming,

      submitText,
      userInput,
      messages,
      events,
      streamNodes,

      loading,
      ready,
    };
  },
});
</script>

// packages/grapys-react/src/views/GraphRunner.tsx
import React, { useState, useEffect, useCallback } from "react";
import { GraphAI, GraphData } from "graphai";
import * as agents from "@graphai/vanilla";
import { openAIAgent } from "@graphai/openai_agent";
import { geminiAgent } from "@graphai/gemini_agent";
// import  geminiAgent from "../agents/gemini_agent";
import { anthropicAgent } from "@graphai/anthropic_agent";
import tinyswallowAgent, { modelLoad, loadEngine, CallbackReport } from "../agents/tinyswallow";
import { useTextInputEvent } from "../agents/event_react";
import Chat from "./Chat";
import { useLocalStore } from "../store";
import { useStreamData } from "../utils/react-plugin/stream";
import { useChatPlugin } from "../utils/react-plugin/chat";

import { graphConfigs } from "../graph";

const GraphRunner: React.FC<{ graphData: GraphData }> = ({ graphData }) => {
  const [isRunning, setIsRunning] = useState(false);
  const streamNodes = useLocalStore((state) => state.streamNodes);
  const resultNodes = useLocalStore((state) => state.resultNodes);

  useEffect(() => {
    loadEngine();
  }, []);

  const { eventAgent, userInput, setUserInput, events, submitText } = useTextInputEvent();
  const { messages, chatMessagePlugin } = useChatPlugin();
  const { streamData, streamAgentFilter, streamPlugin, isStreaming } = useStreamData();

  const agentFilters = [
    {
      name: "streamAgentFilter",
      agent: streamAgentFilter,
    },
  ];

  const [loading, setLoading] = useState("");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    modelLoad((report: CallbackReport) => {
      if (report.progress === 1) {
        setReady(true);
      }
      setLoading(report.text);
      console.log(report.text);
    });
  }, []);

  let graphai: GraphAI | null = null;
  const run = useCallback(async () => {
    setIsRunning(true);
    graphai = new GraphAI(
      graphData,
      {
        ...agents,
        openAIAgent,
        anthropicAgent,
        geminiAgent,
        eventAgent,
        tinyswallowAgent,
      },
      {
        agentFilters,
        config: graphConfigs,
      },
    );
    graphai.registerCallback(streamPlugin(streamNodes()));
    graphai.registerCallback(chatMessagePlugin(resultNodes()));

    try {
      await graphai.run();
    } catch (error) {
      console.log(error);
    }
  }, [eventAgent, streamPlugin, chatMessagePlugin]);

  const abort = useCallback(() => {
    try {
      if (isRunning && graphai) {
        graphai.abort();
        graphai = null;
      }
    } catch (error) {
      console.log(error);
    } finally {
      setIsRunning(false);
    }
  });

  return (
    <div>
      <div className="items-center justify-center text-center">
        <div className="mt-2">
          <Chat messages={messages} isStreaming={isStreaming} streamData={streamData} streamNodeIds={streamNodes()} />
        </div>
        <div className="mt-2">
          <button
            onClick={run}
            className={`m-1 cursor-pointer items-center rounded-full px-4 py-2 font-bold text-white hover:bg-sky-700 ${
              isRunning ? "bg-sky-200" : "bg-sky-500"
            }`}
            disabled={isRunning}
          >
            Run
          </button>
          <button
            onClick={abort}
            className={`m-1 cursor-pointer items-center rounded-full px-4 py-2 font-bold text-white hover:bg-sky-700 ${
              !isRunning ? "bg-sky-200" : "bg-sky-500"
            }`}
            disabled={!isRunning}
          >
            Stop
          </button>
        </div>

        <div>
          <div className="m-auto my-4 w-10/12">
            {events.length > 0 && <div className="hidden font-bold text-red-600">Write message to bot!!</div>}
            <div className="flex">
              <input
                value={userInput}
                onChange={(e) => {
                  setUserInput(e.target.value);
                }}
                className="flex-1 rounded-md border-2 p-2"
                disabled={events.length === 0}
              />
              <button
                className={`ml-1 flex-none cursor-pointer items-center rounded-md px-4 py-2 font-bold text-white hover:bg-sky-700 ${
                  events.length === 0 ? "bg-sky-200" : "bg-sky-500"
                }`}
                onClick={() => {
                  if (events.length > 0) {
                    submitText(events[0]);
                  }
                }}
              >
                Submit
              </button>
            </div>
          </div>
        </div>
        {!ready ? <div>Loading web llm model</div> : <div>Ready!</div>}
        <div>{loading}</div>
      </div>
    </div>
  );
};

export default GraphRunner;
