// packages/grapys-vue/src/views/Node.vue
<template>
  <div
    class="absolute flex w-36 cursor-grab flex-col rounded-md text-center text-white select-none"
    :class="nodeMainClass(expectNearNode, nodeData)"
    :style="{
      transform: transform,
      cursor: isDragging ? 'grabbing' : 'grab',
    }"
    ref="thisRef"
    @mousedown="onStartNode"
    @touchstart="onStartNode"
  >
    <div @dblclick="(e) => openNodeMenu(e)">
      <div class="w-full rounded-t-md py-1 text-center leading-none" :class="nodeHeaderClass(expectNearNode, nodeData)">
        {{ nodeData.nodeId }}
      </div>
      <div class="w-full py-1 text-center text-xs leading-none" v-if="nodeData.type === 'computed'" :class="nodeHeaderClass(expectNearNode, nodeData)">
        {{ nodeData.data.guiAgentId?.replace(/Agent$/, "") }}
      </div>
    </div>
    <div class="mt-1 flex flex-col items-end">
      <div v-for="(output, index) in edgeIO.outputs" :key="['out', output.name, index].join('-')" class="relative flex items-center" ref="outputsRef">
        <span class="mr-2 text-xs whitespace-nowrap">{{ output.name }}</span>
        <div
          class="absolute right-[-10px] h-4 w-4 min-w-[12px] rounded-full"
          :class="nodeOutputClass(isExpectNearButton('inbound', index), nodeData)"
          @mousedown="(e) => onStartEdge(e, 'outbound', index)"
          @touchstart="(e) => onStartEdge(e, 'outbound', index)"
        ></div>
      </div>
    </div>

    <div class="mt-1 mb-1 flex flex-col items-start">
      <div v-for="(input, index) in edgeIO.inputs" :key="['in', input.name, index].join('-')" class="relative flex items-center" ref="inputsRef">
        <div
          class="absolute left-[-10px] h-4 w-4 min-w-[12px] rounded-full"
          :class="nodeInputClass(isExpectNearButton('outbound', index), nodeData)"
          @mousedown="(e) => onStartEdge(e, 'inbound', index)"
          @touchstart="(e) => onStartEdge(e, 'inbound', index)"
        ></div>
        <span class="ml-2 text-xs whitespace-nowrap">{{ input.name }}</span>
      </div>
    </div>
    <div class="flex w-full flex-col gap-1 p-2" v-if="nodeData.type === 'static'">
      <NodeStaticValue :node-data="nodeData" @focus-event="focusEvent" @blur-event="blurEvent" @update-value="updateValue" />
    </div>
    <div class="flex w-full flex-col gap-1 p-2" v-if="nodeData.type === 'computed'">
      <NodeComputedParams :node-data="nodeData" @focus-event="focusEvent" @blur-event="blurEvent" :node-index="nodeIndex" />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, watchEffect, computed, PropType, onMounted } from "vue";
import type { GUINodeData, GUINearestData, NewEdgeEventDirection, UpdateStaticValue } from "../utils/gui/type";
import { getClientPos } from "../utils/gui/utils";
import { agentProfiles, staticNodeParams } from "../utils/gui/data";
import { nodeMainClass, nodeHeaderClass, nodeOutputClass, nodeInputClass } from "../utils/gui/classUtils";

import NodeStaticValue from "./NodeStaticValue.vue";
import NodeComputedParams from "./NodeComputedParams.vue";

export default defineComponent({
  components: {
    NodeStaticValue,
    NodeComputedParams,
  },
  props: {
    nodeData: {
      type: Object as PropType<GUINodeData>,
      required: true,
    },
    nearestData: {
      type: Object as PropType<GUINearestData>,
      default: undefined,
    },
    nodeIndex: {
      type: Number,
      required: true,
    },
  },
  emits: ["updatePosition", "savePosition", "newEdgeStart", "newEdge", "newEdgeEnd", "updateStaticNodeValue", "openNodeMenu"],
  setup(props, ctx) {
    const agentParams = props.nodeData.type === "computed" ? agentProfiles[props.nodeData.data.guiAgentId ?? ""] : staticNodeParams;

    const thisRef = ref();
    const inputsRef = ref<HTMLElement[]>([]);
    const outputsRef = ref<HTMLElement[]>([]);

    const isDragging = ref(false);
    const isNewEdge = ref(false);
    const offset = ref({ x: 0, y: 0 });

    const startPosition = { x: 0, y: 0 };
    let d = 0;
    const onStartNode = (event: MouseEvent | TouchEvent) => {
      console.log("node");
      if (isNewEdge.value) {
        return;
      }
      isDragging.value = true;
      const { clientX, clientY } = getClientPos(event);
      const position = props.nodeData.position;
      offset.value.x = clientX - position.x;
      offset.value.y = clientY - position.y;

      // for update detection
      startPosition.x = position.x;
      startPosition.y = position.y;
      d = 0;
    };

    const getWH = () => {
      const rect = thisRef.value.getBoundingClientRect();
      const parentTop = rect.top;

      const getCenterHeight = (el: HTMLElement) => {
        const oRect = el.getBoundingClientRect();
        return oRect.top - parentTop + oRect.height / 2;
      };
      const outputCenters = outputsRef.value.map(getCenterHeight);
      const inputCenters = inputsRef.value.map(getCenterHeight);
      return {
        width: rect.width,
        height: rect.height,
        outputCenters,
        inputCenters,
      };
    };
    onMounted(() => {
      ctx.emit("updatePosition", getWH());
    });

    const onMoveNode = (event: MouseEvent | TouchEvent) => {
      if (!isDragging.value) return;
      const { clientX, clientY } = getClientPos(event);
      const x = clientX - offset.value.x;
      const y = clientY - offset.value.y;
      const newPosition = { ...getWH(), x, y };
      ctx.emit("updatePosition", newPosition);
      d = (startPosition.x - x) ** 2 + (startPosition.y - y) ** 2;
    };

    const onEndNode = () => {
      isDragging.value = false;
      if (d > 4) {
        ctx.emit("savePosition");
      }
    };

    // edge event
    const onStartEdge = (event: MouseEvent | TouchEvent, direction: NewEdgeEventDirection, index: number) => {
      console.log("edge", event);
      isNewEdge.value = true;
      const { clientX, clientY } = getClientPos(event);
      ctx.emit("newEdgeStart", {
        nodeId: props.nodeData.nodeId,
        x: clientX,
        y: clientY,
        index,
        direction,
      });
    };
    const onEndEdge = () => {
      isNewEdge.value = false;
      ctx.emit("newEdgeEnd", {});
    };
    const onMoveEdge = (event: MouseEvent | TouchEvent) => {
      if (!isNewEdge.value) return;
      const { clientX, clientY } = getClientPos(event);
      ctx.emit("newEdge", { x: clientX, y: clientY });
    };
    // end of edge event

    const edgeIO = agentParams;

    watchEffect((onCleanup) => {
      if (isDragging.value) {
        window.addEventListener("mousemove", onMoveNode);
        window.addEventListener("mouseup", onEndNode);
        window.addEventListener("touchmove", onMoveNode, { passive: false });
        window.addEventListener("touchend", onEndNode);
        onCleanup(() => {
          window.removeEventListener("mousemove", onMoveNode);
          window.removeEventListener("mouseup", onEndNode);
          window.removeEventListener("touchmove", onMoveNode);
          window.removeEventListener("touchend", onEndNode);
        });
      }
    });

    watchEffect((onCleanup) => {
      if (isNewEdge.value) {
        window.addEventListener("mousemove", onMoveEdge);
        window.addEventListener("mouseup", onEndEdge);
        window.addEventListener("touchmove", onMoveEdge, { passive: false });
        window.addEventListener("touchend", onEndEdge);
        onCleanup(() => {
          window.removeEventListener("mousemove", onMoveEdge);
          window.removeEventListener("mouseup", onEndEdge);
          window.removeEventListener("touchmove", onMoveEdge);
          window.removeEventListener("touchend", onEndEdge);
        });
      }
    });

    const transform = computed(() => {
      return `translate(${props.nodeData.position.x}px, ${props.nodeData.position.y}px)`;
    });
    const expectNearNode = computed(() => {
      return props.nodeData.nodeId === props.nearestData?.nodeId;
    });

    const isExpectNearButton = (direction: NewEdgeEventDirection, index: number) => {
      if (!expectNearNode.value) {
        return false;
      }
      return props.nearestData?.direction === direction && props.nearestData?.index === index;
    };

    let currentWidth = 0;
    let currentHeight = 0;
    const focusEvent = () => {
      currentWidth = thisRef.value.offsetWidth;
      currentHeight = thisRef.value.offsetHeight;
      thisRef.value.style.width = currentWidth * 3 + "px";
      thisRef.value.style.height = currentHeight * 3 + "px";
      thisRef.value.style.zIndex = 100;
      ctx.emit("updatePosition", getWH());
    };
    const blurEvent = () => {
      thisRef.value.style.width = currentWidth + "px";
      thisRef.value.style.height = currentHeight + "px";
      thisRef.value.style.zIndex = 1;
      ctx.emit("updatePosition", getWH());
    };
    const updateValue = (value: UpdateStaticValue) => {
      ctx.emit("updateStaticNodeValue", value);
    };
    const openNodeMenu = (event: MouseEvent) => {
      ctx.emit("openNodeMenu", event);
    };
    return {
      focusEvent,
      blurEvent,

      transform,
      onStartNode,
      isDragging,
      edgeIO,
      thisRef,
      isNewEdge,
      onStartEdge,

      inputsRef,
      outputsRef,

      expectNearNode,
      isExpectNearButton,

      updateValue,
      openNodeMenu,
      // helper
      nodeMainClass,
      nodeHeaderClass,
      nodeOutputClass,
      nodeInputClass,
    };
  },
});
</script>

// packages/grapys-react/src/views/Node.tsx
import React, { useRef, useState, useEffect, useCallback } from "react";
import type { GUINodeData, GUINearestData, NewEdgeEventDirection, UpdateStaticValue } from "../utils/gui/type";
import { getClientPos } from "../utils/gui/utils";
import {
  nodeMainClass,
  nodeHeaderClass,
  nodeOutputClass,
  nodeInputClass,
} from "../utils/gui/classUtils";


import { agentProfiles, staticNodeParams } from "../utils/gui/data";
import { useLocalStore } from "../store/index";

import NodeStaticValue from "./NodeStaticValue";
import NodeComputedParams from "./NodeComputedParams";
interface NodeProps {
  nodeData: GUINodeData;
  nearestData?: GUINearestData;
  nodeIndex: number;
  onUpdatePosition: (position: any) => void;
  onSavePosition: () => void;
  onNewEdgeStart: (event: any) => void;
  onNewEdge: (event: any) => void;
  onNewEdgeEnd: (event: any) => void;
  onOpenNodeMenu: (event: any) => void;
}

const Node: React.FC<NodeProps> = ({
  nodeData,
  nearestData,
  nodeIndex,
  onUpdatePosition,
  onSavePosition,
  onNewEdgeStart,
  onNewEdge,
  onNewEdgeEnd,
  onOpenNodeMenu,
}) => {
  const agentParams =
    nodeData.type === "computed"
      ? agentProfiles[nodeData.data.guiAgentId ?? ""]
      : staticNodeParams;

  const thisRef = useRef<HTMLDivElement>(null);
  const inputsRef = useRef<HTMLDivElement[]>([]);
  const outputsRef = useRef<HTMLDivElement[]>([]);
  const [isDragging, setIsDragging] = useState(false);
  const [isNewEdge, setIsNewEdge] = useState(false);
  const [offset, setOffset] = useState({ x: 0, y: 0 });
  const startPosition = useRef({ x: 0, y: 0 });
  const distanceMoved = useRef(0);

  const updateNodePosition = useLocalStore((state) => state.updateNodePosition);

  const transformStyle = {
    transform: `translate(${nodeData?.position?.x ?? 0}px, ${nodeData?.position?.y ?? 0}px)`,
    cursor: isDragging ? "grabbing" : "grab",
  };

  const getWH = () => {
    if (!thisRef.current) {
      return { width: 0, height: 0, outputCenters: [], inputCenters: [] };
    }
    const rect = thisRef.current.getBoundingClientRect();
    const parentTop = rect.top;

    const getCenterHeight = (el: HTMLElement) => {
      const oRect = el.getBoundingClientRect();
      return oRect.top - parentTop + oRect.height / 2;
    };

    return {
      width: rect.width,
      height: rect.height,
      outputCenters: outputsRef.current.map(getCenterHeight),
      inputCenters: inputsRef.current.map(getCenterHeight),
    };
  };
  useEffect(() => {
    onUpdatePosition(getWH());
  }, []);

  const onStartNode = useCallback(
    (event: React.MouseEvent | React.TouchEvent) => {
      if (isNewEdge) return;
      setIsDragging(true);
      const { clientX, clientY } = getClientPos(event);
      setOffset({
        x: clientX - nodeData.position.x,
        y: clientY - nodeData.position.y,
      });
      startPosition.current = {
        x: nodeData.position.x,
        y: nodeData.position.y,
      };
      distanceMoved.current = 0;
    },
    [nodeData.position, isNewEdge],
  );

  const onMoveNode = useCallback(
    (event: MouseEvent | TouchEvent) => {
      if (!isDragging) return;
      const { clientX, clientY } = getClientPos(event);
      const x = clientX - offset.x;
      const y = clientY - offset.y;
      onUpdatePosition({ ...getWH(), x, y });
      distanceMoved.current =
        (startPosition.current.x - x) ** 2 + (startPosition.current.y - y) ** 2;
    },
    [isDragging, offset, onUpdatePosition],
  );

  const onEndNode = useCallback(() => {
    setIsDragging(false);
    if (distanceMoved.current > 4) {
      onSavePosition();
    }
  }, [onSavePosition]);

  const edgeIO = agentParams;

  const onStartEdge = useCallback(
    (
      event: React.MouseEvent | React.TouchEvent,
      direction: string,
      index: number,
    ) => {
      event.stopPropagation();
      setIsNewEdge(true);
      const { clientX, clientY } = getClientPos(event);
      onNewEdgeStart({
        nodeId: nodeData.nodeId,
        x: clientX,
        y: clientY,
        index,
        direction,
      });
    },
    [onNewEdgeStart, nodeData.nodeId],
  );

  const onMoveEdge = useCallback(
    (event: MouseEvent | TouchEvent) => {
      if (!isNewEdge) return;
      const { clientX, clientY } = getClientPos(event);
      onNewEdge({ x: clientX, y: clientY });
    },
    [isNewEdge, onNewEdge],
  );

  const onEndEdge = useCallback(() => {
    setIsNewEdge(false);
    onNewEdgeEnd({});
  }, [onNewEdgeEnd]);

  useEffect(() => {
    if (isDragging) {
      window.addEventListener("mousemove", onMoveNode);
      window.addEventListener("mouseup", onEndNode);
      window.addEventListener("touchmove", onMoveNode, { passive: false });
      window.addEventListener("touchend", onEndNode);
      return () => {
        window.removeEventListener("mousemove", onMoveNode);
        window.removeEventListener("mouseup", onEndNode);
        window.removeEventListener("touchmove", onMoveNode);
        window.removeEventListener("touchend", onEndNode);
      };
    }
  }, [isDragging, onMoveNode, onEndNode]);

  useEffect(() => {
    if (isNewEdge) {
      window.addEventListener("mousemove", onMoveEdge);
      window.addEventListener("mouseup", onEndEdge);
      window.addEventListener("touchmove", onMoveEdge, { passive: false });
      window.addEventListener("touchend", onEndEdge);
      return () => {
        window.removeEventListener("mousemove", onMoveEdge);
        window.removeEventListener("mouseup", onEndEdge);
        window.removeEventListener("touchmove", onMoveEdge);
        window.removeEventListener("touchend", onEndEdge);
      };
    }
  }, [isNewEdge, onMoveEdge, onEndEdge]);

  const expectNearNode = nodeData.nodeId === nearestData?.nodeId;
  const isExpectNearButton = (direction: NewEdgeEventDirection, index: number) => {
    if (!expectNearNode) {
      return false;
    }
    return nearestData?.direction === direction && nearestData?.index === index;
  };
  
  const [currentWidth, setCurrentWidth] = useState(0);
  const [currentHeight, setCurrentHeight] = useState(0);
  const onFocus = () => {
    setCurrentWidth(thisRef.current.offsetWidth);
    setCurrentHeight(thisRef.current.offsetHeight);
    thisRef.current.style.width = thisRef.current.offsetWidth * 3 + "px";
    thisRef.current.style.height = thisRef.current.offsetHeight * 3 + "px";
    thisRef.current.style.zIndex = 100;
    onUpdatePosition(getWH());
  };
  const onBlur = () => {
    thisRef.current.style.width = currentWidth + "px";
    thisRef.current.style.height = currentHeight + "px";
    thisRef.current.style.zIndex = 1;
    onUpdatePosition(getWH());
  };
  const onUpdateValue = (value: UpdateStaticValue) => {
    console.log(value);
    // TODO
  };
  const openNodeMenu = (event: MouseEvent) => {
    // TODO
    // ctx.emit("openNodeMenu", event);
  };

  return (
    <div
      className={`absolute flex w-36 cursor-grab flex-col rounded-md text-center text-white select-none ${nodeMainClass(expectNearNode, nodeData)}`}
      style={transformStyle}
      ref={thisRef}
      onMouseDown={onStartNode}
      onTouchStart={onStartNode}
    >
      <div onDoubleClick={onOpenNodeMenu}>
        <div
          className={`w-full rounded-t-md py-1 text-center leading-none ${nodeHeaderClass(expectNearNode, nodeData)}`}
        >
          {nodeData.nodeId}
        </div>
        {nodeData.type === "computed" && (
          <div
            className={`w-full py-1 text-center text-xs leading-none ${nodeHeaderClass(expectNearNode, nodeData)}`}
          >
            {nodeData.data.guiAgentId?.replace(/Agent$/, "")}
          </div>
        )}
      </div>

      <div className="mt-1 flex flex-col items-end">
        {(edgeIO.outputs ?? []).map((output: any, index: number) => (
          <div
            key={`out-${output.name}-${index}`}
            className="relative flex items-center"
            ref={(el) => (outputsRef.current[index] = el!)}
          >
            <span className="mr-2 text-xs whitespace-nowrap">
              {output.name}
            </span>
            <div
          className={`absolute right-[-10px] h-4 w-4 min-w-[12px] rounded-full ${nodeOutputClass(isExpectNearButton('inbound', index), nodeData)}`}
              onMouseDown={(e) => onStartEdge(e, "outbound", index)}
            ></div>
          </div>
        ))}
      </div>

      <div className="mt-1 mb-1 flex flex-col items-start">
        {(edgeIO.inputs ?? []).map((input: any, index: number) => (
          <div
            key={`in-${input.name}-${index}`}
            className="relative flex items-center"
            ref={(el) => (inputsRef.current[index] = el!)}
          >
            <div
              className={`absolute left-[-10px] h-4 w-4 min-w-[12px] rounded-full  ${nodeInputClass(isExpectNearButton('outbound', index), nodeData)}`}
              onMouseDown={(e) => onStartEdge(e, "inbound", index)}
            ></div>
            <span className="ml-2 text-xs whitespace-nowrap">{input.name}</span>
          </div>
        ))}
      </div>

      {nodeData.type === "static" && (
        <div className="flex w-full flex-col gap-1 p-2">
          <NodeStaticValue
            nodeData={nodeData}
            onFocus={onFocus}
            onBlur={onBlur}
            onUpdateValue={onUpdateValue}
          />
        </div>
      )}
      {nodeData.type === "computed" && (
        <div className="flex w-full flex-col gap-1 p-2">
          <NodeComputedParams
            nodeData={nodeData}
            nodeIndex={nodeIndex}
            onFocus={onFocus}
            onBlur={onBlur}
          />
        </div>
      )}
    </div>
  );
};

export default Node;
